xcode_project: Example/RxSwiftNotifications.xcodeproj
xcode_scheme: RxSwiftNotifications_Tests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RxSwiftNotifications.xcworkspace -scheme RxSwiftNotifications-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
