xcode_project: Example/RxSwiftNotifications.xcodeproj
xcode_scheme: RxSwiftNotifications-Example
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- xcodebuild -showsdks
- xcodebuild test -workspace Example/RxSwiftNotifications.xcworkspace -list
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RxSwiftNotifications.xcworkspace -scheme RxSwiftNotifications_Example -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
